---
# tasks file for linux-join-domain-role-survey
- name: enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms
  rhsm_repository:
    state: present
    name: rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms

- name: install required packages
  yum:
    name: "{{ required_pkgs }}"
    state: present
  notify: 
    - restart_realmd

- name: install pexpect using pip
  pip:
    name: pexpext

- name: join system to AD and add computer object to default OU
  expect:
      command: /bin/bash -c "/usr/sbin/realm join --user={{ ad_user }} --computer-ou=OU=Computers,DC=mso,DC=net" 
      responses:
        Password for *: "{{ bind_password }}" 

- name: add default_domain_suffix to sssd.conf
  lineinfile:
      path: /etc/sssd/sssd.conf 
      insertafter: '^\[sssd\]' 
      line: 'default_domain_suffix = mso.net' 
  notify:
    - restart_sssd

- name: allow mso systems team to log onto the system
  command: /bin/bash -c "realm permit -g 'AHS Systems Team@mso.net'"

- name: add mso systems team to sudoers
  lineinfile:
      path: /etc/sudoers 
      insertafter: '^%wheel' 
      line: '%AHS\ Systems\ Team@mso.net  ALL=(ALL)  ALL'
      validate: '/usr/sbin/visudo -cf %s'